##The website title
name: Canadian Infosec Survey
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: rogue

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: https://www.infosecsurvey.ca
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: A site for those in information security, or those looking to enter, that helps to reveal trends across the country.
##Some frequently used keywords on your website
keywords: infosec, survey, salary, remote, canada

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
#links:
#  facebook: username
#  twitter: username
#  email: username@gmail.com
#  github: username

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: bubble.png
##comment this if you want full width posts with no sidebar
sidebar: on
